[gcp_service_account]
type = "service_account"
project_id = "named-haven-472704-m7"
private_key_id = "adf595509acc3bacacdb9931184d3e16a832150b"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCvkRLzhv+OklAT\nqsoCLHx+FNz/LgKW8KNdyjZ+o44b3fFYubi82rAplURr0bwUHh78YHamdY6ixh0K\nsNwVgruFaYk1mBeLfPcBZJEFpuwZFmUSmOZGGxjZfqoC4uk1Hu5+aksRP9BV5GMy\nJSLWELK+Cf80oIrO5+oeQ4XIFiuMvgA4S88CfC8nP61mordOiVzd9IrHQQ1Yrgnz\nTSDlqGxRxVUSlCw9lk/o7oHinu920sQHHTnX7mUXhZxgE1i37PsWtoUPgrXNDBkm\nyi2R/mvPrbok/rZtHH9y73i4QFohAT0VdV+ifSw4p1r6A+y7AuM7tyXLQoM/surH\njY3mPbWHAgMBAAECggEAFC8jFSFTlyIGF8S+VbKkm2Atqh6xiIXg2kMJsdR+3YBO\nI2uyq++eaiFxjM2/iDaQTGaQrYF9ZQROyXBc1RJDGcrwzdsO9efng976d0JiCV5U\nP2eZrbymxjZ0OEG7GvLT62+v8qs5+e34Y4b2ctLXodaHYxcD7lamSVVs93xpBFSQ\nwZWzr1htnPJzxHg98jmGpW9dFZqDxLf2hWYFf1l6UYE4SnJpPg+FFT8o4G017pKz\noopU01KxbVJVzhwLo8qjcN7xUv3+kwt880iZkcnRQHrEAgrCr0rJmPRN7pH/4+Fi\nHh38Dl40Sk+otdQ8Wro/EsQaPnqEHrkcXPjFz/ZYHQKBgQDoSrW+Tb9/N3/SttZK\ncaXbE0b56vFVE3buKNFDAqNVPigAiT5V0iWOpQWP8O5AfXbIbBCuRtpLV7CkL/Hs\nG+TyK3ldg8xbWbPBiTu1J4OBwLOCMYqgLsnnOjlWT4RHRTykW9npeY92oij7Dp3X\ndRy0E8gFBn8fvmvu98KGHLAsjQKBgQDBfEHYEI5gwdx4/QcspbpZI7borOSg5zoX\nJAu+/TM1URg/xVT2+Hy6GqL3FrSHF6UyP99toLC56qar5Pp6ZImU1gYwowbXuPqZ\nieYri/OMZAV3I0i1HkiB1uUYNAnh5tF0+y3ymxUiYb77NkTdQ11MJ6xc3wkfivPw\n2e48618nYwKBgFZsjWfLR2cOgAkmq12xINL8Phj3l2hewI3lM84pqhkp8foZFc8a\nS4zhysr+CbaGt23j/uTISalka7z6dZix3CFZmWL4iUyneCCWbVd95wicaG0U/42P\nOuFDoVeCaCWYFfLUlaOu7Xhm5rZZftJNqSs6fN2ZyCxITaHwHjiFbep1AoGBAKqW\nWCMcLbuHEFAnngyyLULsJxarYIOwednvMN/5sw1d60hGPevlF2qpk2bQQOgeY8qS\n3/VyyH2SMdK59lC0lUyBCkIVajIF6AQ4vZNFN7xebyckF7V/9qNrCN82+kOOUruV\nvWP5cT+3+D7aEQsXmolLLT9QcWW7B+og6lgRmPpLAoGBALpZZivOzl/6jrRuGTwH\nksaKWTDwrRYbipONsE9CWCgfMr78XppixoyHyi1+ibP1r+tuPQJSFqhd8ty4My6n\nbN0UFliH+TW3A5M1nzuSn6D3k5jEX1aYaPgO5se1DEuxXbt95p4LNveMn8ZyoxuN\nXYtkMRruurmTmzR0JzfaAA3f\n-----END PRIVATE KEY-----\n",
client_email = "ichidaisai@named-haven-472704-m7.iam.gserviceaccount.com"
client_id = "100060453556089541255"
token_uri = "https://oauth2.googleapis.com/token"

[app]
# Google スプレッドシートの URL の /d/<この部分>/ が ID
gsheet_id = "1nJim_Bz9nrUyQrAoVNPAQ-nGn9eN_s5Ku1MEf7BnX9M/edit?gid=0#gid=0"

# 提供者が指定する候補（あとからここを書き換えるだけでOK）
allowed_dates = ["2025-10-25", "2025-10-26"]
allowed_places = ["メインステージ","アルカイゾ","ダンス練習場","調理室","レッスンルーム"]

# 固定の時間軸
day_start = "09:00"
day_end   = "18:00"
